config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  get 'home/index', as: 'home'

  get 'users/profile', to: 'users#profile', as: 'profile'

  post 'users/profile', to: 'users#create_activity'

  get 'activities/new'

  get 'activities/index'

  post 'activities/favorite', to: 'activities#favorite', as: 'favorite_activity'

  get 'access/forgot_password'

  get 'login', to: "access#login", as: 'login'

  get 'signup', to: "access#signup", as: 'signup'

  post 'login', to: "access#attempt_login"

  post 'signup', to: "access#create"

  get 'home', to: "access#home"

  get 'logout', to: "access#logout"

  get 'forgot', to: 'access#forgot_password'
  post 'send_reset', to: 'access#send_reset'
  get 'reset/:token', to: 'access#reset_password'
  post 'update_password', to: 'access#update_password'



  resources :users do
    resources :activities
    # resources :profile
  end

  resources :activities
  
end

app/models/activity.rb
class Activity < ActiveRecord::Base
	belongs_to :user
	
  has_many :favorites
  has_many :favorited, through: :favorites, source: :user
  # has_many :taco, through: :join_table, source: :model_trying_to_return

  def self.fun_activities_with_user time, user=nil
  	if user
  		return fun_activities(time).where("id not in (?)", user.favorited.select("activities.id"))
  	end
  		
  	fun_activities time
  end

  def self.convert_to_minutes days, hours, minutes
    return (days.to_i * 24 * 60) + (hours.to_i * 60) + minutes.to_i
  end

  private

  def self.fun_activities time
  	 where("time_min <= " + time.to_s).where("time_max IS NULL OR time_max >= " + time.to_s)
  end
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
	belongs_to :user
	belongs_to :activity
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password

	validates :username,
    presence: true,
    uniqueness: true

	has_many :activities

	has_many :favorites
	has_many :favorited, through: :favorites, source: :activity
	# has_many :taco, through: :join_table, source: :model_trying_to_return
end

app/controllers/access_controller.rb
class AccessController < ApplicationController
  before_action :confirm_logged_in, only: [:profile]
  before_action :prevent_login_signup, only: [:signup, :login]

  def reset_password
    @token = params[:token]
    @user = User.find_by :reset_token => @token
    if @user.nil?
      flash[:error] = "Invalid reset token"
      render :login
    else  
      render :reset_password
    end
  end

  #post '/send_reset' => 'user#reset_password'
  def send_reset
    # username in param
    username = params[:username]
    user =  User.find_by username: username
    if user.nil?
      flash[:error] = "No such user:" + username
    else
      # create and save reset token on user
      user.reset_token = (0...16).map { (65 + rand(26)).chr }.join
      user.save
      UserMailer.forgot_password_email(user).deliver
      flash[:success] = "Please check your email for reset instructions ..."
    end
    render :forgot_password
  end

  def update_password
    user_params = params.permit(:username, :password, :password_confirmation)
    @user = User.find_by username: user_params[:username]
    @user.update_attributes(password: user_params[:password], password_confirmation: user_params[:password_confirmation])
    flash[:success] = "Your password has changed, try it out ..."
    render :login
  end

  def signup
    @user = User.new
  end

   def create
    @user = User.create(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "You are now logged in!"
      UserMailer.signup_confirmation(@user).deliver
      redirect_to home_path
    else
      render :signup
    end
   end

  def login
  end

  def attempt_login

    if params[:username].present? && params[:password].present?
      found_user = User.where(username: params[:username]).first
      if found_user
        authorized_user = found_user.authenticate(params[:password])
      end
    end

    if !found_user
      flash.now[:alert] = "Invalid username"
      render :login

    elsif !authorized_user
      flash[:alert] = "Invalid password"
      render :login

    else
      session[:user_id] = authorized_user.id
      flash[:success] = "You are now logged in."
      redirect_to home_path
    end

  end

  def home

  end

  def logout
    session[:user_id] = nil
    flash[:notice] = "Logged out"
    redirect_to home_path
  end

  private
  def user_params
    params.require(:user).permit(:username, :password, :password_digest, :location, :description)
  end

  def confirm_logged_in
    unless session[:user_id]
      redirect_to login_path, alert: "Please log in"
    end
  end

  def prevent_login_signup
    if session[:user_id]
      redirect_to home_path
    end
  end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  def new
  	if session[:user_id] 
	  	@current_user = User.find session[:user_id] 
	  	@new_activity = @current_user.activities.new
  	else 
  		redirect_to '/login'
  	end
  end

  def index
    if params["days"] =~ %r/[^0-9]/ || params["hours"] =~ %r/[^0-9]/ || params["minutes"] =~ %r/[^0-9]/
      flash["failure"]= "Yo, numbers only, pls"
      redirect_to home_path
      return
    end
    if params["days"] == ""
      params["days"] = 0
    end
    if params["hours"] == ""
      params["hours"] = 0
    end
    if params["minutes"] == ""
      params["minutes"] = 0
    end
    if params["days"].to_i + params["hours"].to_i + params["minutes"].to_i == 0
      flash["failure"]= "Please input a time greater than zero."
      redirect_to home_path
    end
  	@activity_list = Activity.fun_activities_with_user(Activity.convert_to_minutes(params["days"], params["hours"], params["minutes"]))
    if @activity_list.length == 0
      flash["failure"] = "No results were returned."
      redirect_to home_path
    end
  end

  def create
  	if session[:user_id] 
	  	@current_user = User.find session[:user_id] 
			@current_user.activities.create(activity_params)
      redirect_to home_path
		else
			redirect_to '/login'
		end
  end

  def favorite
    type = params[:type]
    if type == "favorite"
      @current_user = User.find session[:user_id]
      favorite = @current_user.favorites.new
      favorite.activity_id = params[:activity_id]
      favorite.user_id = session[:user_id] 
      favorite.save
      redirect_to :back, notice: 'You favorited #{@activity.title}'
    else
      # Type missing, nothing happens
      redirect_to :back, notice: 'Nothing happened.'
    end
  end



  def show
  	@activity = Activity.find params[:id]
  	@filtered_activities_by_time = Activity.find([15,16])
  end




  private
  def activity_params 
    params.require(:activity).permit(:title, :location, :time_min, :time_max, :description, :img_url, :star_rating )
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	if session[:user_id] 
	  	@current_user = User.find session[:user_id] 
  	end
  end

  # def create
  # 	if session[:user_id] 
	 #  	@current_user = User.find session[:user_id] 
		# 	@current_user.activities.create(activity_params)
  #     redirect_to home_path
		# else
		# 	redirect_to '/login'
		# end
  # end

  # private
  # def activity_params 
  #   params.require(:activity).permit(:title, :location, :time_min, :time_max, :description, :img_url, :star_rating )
  # end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def profile
  	if session[:user_id] 
	  	@current_user = User.find session[:user_id] 
	  	@new_activity = @current_user.activities.new
  	else 
  		redirect_to '/login'
  	end
  end

  def create_activity
  	if session[:user_id] 
	  	@current_user = User.find session[:user_id] 
		@current_user.activities.create(activity_params)
 		redirect_to :back
	else
		redirect_to '/login'
	end
  end

  private
  def activity_params 
    params.require(:activity).permit(:title, :location, :time_min, :time_max, :description, :img_url, :star_rating )
  end

  
end

app/helpers/access_helper.rb
module AccessHelper
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/access/forgot_password.html.erb
<div class="formpic">
<%= render 'layouts/header' %>
	<div class="signuplog-form">
		<p class="center">Enter Username:
		</p>

    
    	<%= form_tag '/send_reset', :method=>'post' do %>
		<p class="center">
     	<% label_tag :username %>
      <%= text_field_tag :username %>
    </p>
    <p class="center-button">
     	<%= submit_tag "Reset Password", class: "btn-clear" %>
    
    </p>
    <% end %>
  </div>
</div>

app/views/access/home.html.erb
<h1>Welcome to our Website!</h1>

<%= link_to "Logout", logout_path, class:"btn btn-danger" %>

app/views/access/login.html.erb
<div class="formpic">
<%= render 'layouts/header' %>
	<div class="signup-box">
		<div class="signuplog-form">
  	<%= form_tag(login_path) do %>
			<p class="center">
  			<%= label_tag(:username)%>
  			<%= text_field_tag(:username, params[:username], autofocus: true)%>
			</p>
			<p class="center">
  			<%= label_tag(:password)%>
  			<%= password_field_tag(:password)%>
			</p>
			<p class="center-button">
  			<%= submit_tag("Log in", class: "btn-clear") %>
			</p>
		<% end %>

			<p class="center"><%= link_to "Don't have an account? Sign up", signup_path%>
			<p class="center"><%= link_to "Forgot Password", forgot_path %></p>

		</div>
	</div>
</div>

app/views/access/reset_password.html.erb
<div class="formpic">

  <%= render 'layouts/header' %>
<div class="row">
  <div class="col-md-6 col-sm-6 col-md-offset-3 col-sm-offset-3">
    
  <%= form_tag(update_password_path, :method=>'post') do %>

    <p class="center">
      <%= text_field_tag(:username, @user.username, readonly: true) %>
    </p>
      
    <p class="center">
   <%= label_tag(:password, "New Password") %> 
   <%= password_field_tag :password %>
   </p>

   <p class="center">
      <%= label_tag(:password_confirmation, "Confirmation") %> 
      <%= password_field_tag :password_confirmation %>
   </p>

    <p class="center-button">
     <%= submit_tag 'Reset Password', class: "btn-clear" %>
    </p>
  <% end %>

  </div>
</div>
</div>

app/views/access/signup.html.erb
<!-- <p class="center-title">Signup</p> -->
<div class="formpic">


	<%= render 'layouts/header' %>
	<div class="signup-box">
		<div class=" container signuplog-form">


		<%= form_for(@user, url: signup_path) do |f|%>

		<p class="center">
  		<%= f.label(:username) %>
  		<%= f.text_field(:username, autofocus: true) %>
		</p>
		<p class="center">
  		<%= f.label(:password) %>
  		<%= f.password_field(:password) %>
		</p>
		<p class="center">
  		<%= f.label(:location) %>
  		<%= f.text_field(:location) %>
		</p>
		<p class="center">
  	<%= f.label(:description) %>
  	<%= f.text_area(:description) %>
		</p>
		<p class="center-button">
  		<%= f.submit("Sign up", class: "btn-clear") %>
		</p>
		<p class="center">
  		<%= link_to "Already have an account?", login_path %>
  	</p>
		<% end %>
	</div>
</div>
</div>

app/views/activities/index.html.erb
<script src="https://maps.googleapis.com/maps/api/js?v=3.exp"></script>

<div id= "header-carousel" class="page-container bored-header clearfix shift-with-hiw">
	<a href="/" id="logo-carousel" class="header-logo pull-left"><img src="<%= image_path('clockblack.png') %>"></a>
				
	<ul class="nav pull-right logged-out list-unstyled medium-right-margin">
		<% if session[:user_id] == nil %>
		<li id="sign_up-carousel" class="pull-left medium-right-margin"> 
			<a href="/signup">Sign Up</a>
		</li>
		<li id="login-carousel" class="pull-left"> 
			<a href="/login">Login</a>
		</li>
		<% else %>
		<li id="login-carousel" class="pull-left"> 
		<a href="/users/profile">Profile</a>
		</li>
		<li id="login-carousel" class="pull-left"> 
			<a href="/logout">Logout</a>
		</li>
			<% end %>
		</ul>
				
			</div>

<div class="wrapper page container">
	<div class="jcarousel-wrapper">
		<div class="jcarousel">
		    <ul>

		      <% for activity in @activity_list %>

		      <li>
		      <div class="act-container">
					 <% if activity.img_url != nil %>	
					 <div class="activity-img">
					 <%= image_tag(activity.img_url) %>
					</div>
					<% end %>

					<div class="act-desc col-3">
					<% if activity.title != nil %>
					
						<div class="title"><%= activity.title %></div>
					<% end %>

					<% if activity.location != nil %>
						<div class="location"><%= activity.location %></div>
					<% end %>
					<% if activity.description != nil %>
						<div class="description"><%= activity.description %></div>
					<% end %>
					<br>
					<% if activity.time_min != nil and activity.time_max != nil %>
						<div class="time-range">Estimated Time: <%= activity.time_min %> to <%= activity.time_max %> minutes </div>
					<% else %>
						<div class="time-range">Time: <%= activity_list.time_min %> minutes</div>
					<% end %>
					<% if activity.location != nil %>
										<div class="time-range"  id="distance<%= activity.id %>">distance </div>
										<div class="time-range" id="walking<%= activity.id %>">walking </div>
								    <div class="time-range" id="biking<%= activity.id %>">biking </div>
								    <div class="time-range" id="driving<%= activity.id %>">driving </div>
								    <div class="time-range" id="message"> </div>
									<% end %>
					<div class="container share-buttons">
						<div class="row">
						<div class="col-md-1">
						<% if session[:user_id] %>
						
						<%= link_to('<img src="assets/heart_icon.png" id="heart-icon">'.html_safe, favorite_activity_path(activity_id: activity.id, type: "favorite"), :method => :post ) %>	
						<% end %> 
						</div>
					<div class="col-md-1" style="padding: 9px 0">
						<a class="twitter-share-button" href="https://twitter.com/share?url=./view/<%= activity.id %>"></a>
					</div>
					<div class="col-md-1 fb-share-button" data-href="./view/<%= activity.id %>" data-layout="button_count">
					</div>
					</div>

					</div> <!-- end share buttons -->
					</div> <!-- end description div -->
					</div><!--  end act container -->

						</li>
	        <% end %>

		    </ul>

		</div> <!-- end jcarousel -->
		
		<!-- Prev/next controls -->
		<a href="#" class="jcarousel-control-prev">&lsaquo; </a>
		<a href="#" class="jcarousel-control-next"> &rsaquo;</a>

		<!-- Pagination -->
		<p class="jcarousel-pagination">
		    <!-- Pagination items will be generated in here -->
		</p>
	</div>	
</div>

<script>
var distance_settings;
var x = document.getElementById("message");

<% @activity_list.each do |activity| %>
  var distance<%= activity.id %> = document.getElementById('distance<%= activity.id %>');
  var walking<%= activity.id %> = document.getElementById('walking<%= activity.id %>');
  var biking<%= activity.id %> = document.getElementById('biking<%= activity.id %>');
  var driving<%= activity.id %> = document.getElementById('driving<%= activity.id %>');
<% end %>


var destinations = [];
<% @activity_list.each do |activity| %>
  destinations.push("<%= activity.location %>");
<% end %>

function getLocation() {
    if (navigator.geolocation) {
        navigator.geolocation.getCurrentPosition(showPosition, showError);
    } else { 
        x.innerHTML = "Geolocation is not supported by this browser.";
    }
}

function showPosition(position) {
  var lat = position.coords.latitude;
  var lon = position.coords.longitude;
  var origin = new google.maps.LatLng(lat, lon);

  distance_settings = {
    origins: [origin],
    destinations: destinations,
    travelMode: google.maps.TravelMode.WALKING,
    unitSystem: google.maps.UnitSystem.IMPERIAL
  };

  var service1 = new google.maps.DistanceMatrixService();
  service1.getDistanceMatrix(distance_settings, callback1);
}

function callback1(response, status) {
  if (status != google.maps.DistanceMatrixStatus.OK) {
    alert('Error was: ' + status);
  } else {
    var origins = response.originAddresses;
    var destinations = response.destinationAddresses;
    
    var origins = response.originAddresses;
    // console.log(origins[0]); return the calculated address for that location
    var destinations = response.destinationAddresses;
    // console.log(destinations[0]); return the calculated address for that location
    
    // there is only one row because there is only one origin  
    for (var i = 0; i < origins.length; i++) {
      var results = response.rows[i].elements;
      var j = 0;
      <% @activity_list.each do |activity| %>
        distance<%= activity.id %>.innerHTML = "distance: " + results[j].distance.text;
        walking<%= activity.id %>.innerHTML = "walking: " + results[j].duration.text;
        j++;
      <% end %>
    }
  }

  var service2 = new google.maps.DistanceMatrixService();
  distance_settings.travelMode = google.maps.TravelMode.BICYCLING;
  service2.getDistanceMatrix(distance_settings, callback2);
}


function callback2(response, status) {
  if (status != google.maps.DistanceMatrixStatus.OK) {
    alert('Error was: ' + status);
  } else {
    var origins = response.originAddresses;
    var destinations = response.destinationAddresses;
    
    var origins = response.originAddresses;
    // console.log(origins[0]); return the calculated address for that location
    var destinations = response.destinationAddresses;
    // console.log(destinations[0]); return the calculated address for that location
    
    // there is only one row because there is only one origin  
    for (var i = 0; i < origins.length; i++) {
      var results = response.rows[i].elements;
      var j = 0;
      <% @activity_list.each do |activity| %>
        biking<%= activity.id %>.innerHTML = "biking: " + results[j].duration.text;
        j++;
      <% end %>
    }
  }

  var service3 = new google.maps.DistanceMatrixService();
  distance_settings.travelMode = google.maps.TravelMode.DRIVING;
  service3.getDistanceMatrix(distance_settings, callback3);
}

function callback3(response, status) {
  if (status != google.maps.DistanceMatrixStatus.OK) {
    alert('Error was: ' + status);
  } else {
    var origins = response.originAddresses;
    var destinations = response.destinationAddresses;
    
    var origins = response.originAddresses;
    // console.log(origins[0]); return the calculated address for that location
    var destinations = response.destinationAddresses;
    // console.log(destinations[0]); return the calculated address for that location
    
    // there is only one row because there is only one origin  
    for (var i = 0; i < origins.length; i++) {
      var results = response.rows[i].elements;
      var j = 0;
      <% @activity_list.each do |activity| %>
        driving<%= activity.id %>.innerHTML = "driving: " + results[j].duration.text;
        j++;
      <% end %>
    }
  }
}


function showError(error) {
    switch(error.code) {
        case error.PERMISSION_DENIED:
            x.innerHTML = "User denied the request for Geolocation."
            break;
        case error.POSITION_UNAVAILABLE:
            x.innerHTML = "Location information is unavailable."
            break;
        case error.TIMEOUT:
            x.innerHTML = "The request to get user location timed out."
            break;
        case error.UNKNOWN_ERROR:
            x.innerHTML = "An unknown error occurred."
            break;
    }
}

getLocation();

</script>

app/views/activities/new.html.erb
<h1>Activities#new</h1>
<p>Find me in app/views/activities/new.html.erb</p>

<%= form_for(@new_activity, url: user_activities_path) do |f|%>
	<div>
	  <%= f.label(:title, class: "control-label") %>
	  <%= f.text_field(:title, autofocus: true, class: "form-control") %>
	</div>

	<div>
	  <%= f.label(:location, class: "control-label") %>
	  <%= f.text_field(:location, autofocus: true, class: "form-control") %>
	</div>

	<div>
	  <%= f.label(:time_min, class: "control-label") %>
	  <%= f.text_field(:time_min, autofocus: true, class: "form-control") %>
	</div>

	<div>
	  <%= f.label(:time_max, class: "control-label") %>
	  <%= f.text_field(:time_max, autofocus: true, class: "form-control") %>
	</div>

	<div>
	  <%= f.label(:description, class: "control-label") %>
	  <%= f.text_field(:description, autofocus: true, class: "form-control") %>
	</div>

	<div>
	  <%= f.label(:img_url,  class: "control-label") %>
	  <%= f.uploadcare_field :img_url, class: "form-control" %>
	</div>

	<div>
	  <%= f.label(:star_rating,  class: "control-label") %>
	  <%= f.text_field(:star_rating,  class: "form-control") %>
	</div>

	<%= f.submit("Add a new activity!", class: "btn btn-lg btn-info") %>
<% end %>

app/views/activities/show.html.erb
<script src="https://maps.googleapis.com/maps/api/js?v=3.exp"></script>


<p>Click the button to get your coordinates.</p>
<button onclick="getLocation()">Try It</button>

<p id="message"> </p>
<br>
<!-- <div id="outputDiv">
  <p>calculating distance and commuting time...</p> 
  <img class="gif1" src="../../assets/gallery_loader.gif" alt="load spinner gif"> 
</div> -->

<% @filtered_activities_by_time.each do |a| %>
  <div id="output_activity<%= a.id %>">
    <p id="origin<%= a.id %>"> </p>
    <p id="destination<%= a.id %>"> </p>
    <p id="distance<%= a.id %>"> </p>
    <p id="time_text"> </p>
    <p id="walking<%= a.id %>"> </p>
    <p id="biking<%= a.id %>"> </p>
    <p id="driving<%= a.id %>"> </p>
  </div>
  <br>
<% end %>



<script>
 var x = document.getElementById("message");

<% @filtered_activities_by_time.each do |a| %>
  var output_activity<%= a.id %> = document.getElementById('output_activity<%= a.id %>');
  var origin<%= a.id %> = document.getElementById('origin<%= a.id %>');
  var destination<%= a.id %> = document.getElementById('destination<%= a.id %>');
  var distance<%= a.id %> = document.getElementById('distance<%= a.id %>');
  var time_text = document.getElementById('time_text');
  var walking<%= a.id %> = document.getElementById('walking<%= a.id %>');
  var biking<%= a.id %> = document.getElementById('biking<%= a.id %>');
  var driving<%= a.id %> = document.getElementById('driving<%= a.id %>');
  
<% end %>
var distance_settings;
// var origin;

var destinations = [];
<% @filtered_activities_by_time.each do |a| %>
  destinations.push("<%= a.location %>");
<% end %>

function getLocation() {
    if (navigator.geolocation) {
        navigator.geolocation.getCurrentPosition(showPosition, showError);
    } else { 
        x.innerHTML = "Geolocation is not supported by this browser.";
    }
}

function showPosition(position) {
  var lat = position.coords.latitude;
  var lon = position.coords.longitude;
  // x.innerHTML = "Latitude: " + lat + 
  // "<br>Longitude: " + lon; 
  var origin = new google.maps.LatLng(lat, lon);

  distance_settings = {
    origins: [origin],
    destinations: destinations,
    travelMode: google.maps.TravelMode.WALKING,
    unitSystem: google.maps.UnitSystem.IMPERIAL
  };

  var service1 = new google.maps.DistanceMatrixService();
  service1.getDistanceMatrix(distance_settings, callback1);
}

function callback1(response, status) {
  if (status != google.maps.DistanceMatrixStatus.OK) {
    alert('Error was: ' + status);
  } else {
    var origins = response.originAddresses;
    var destinations = response.destinationAddresses;
    
    var origins = response.originAddresses;
    // console.log(origins[0]); return the calculated address for that location
    var destinations = response.destinationAddresses;
    // console.log(destinations[0]); return the calculated address for that location
    
    // there is only one row because there is only one origin  
    for (var i = 0; i < origins.length; i++) {
      var results = response.rows[i].elements;
      var j = 0;
      <% @filtered_activities_by_time.each do |a| %>

        origin<%= a.id %>.innerHTML = "origin: " + origins[i];
        destination<%= a.id %>.innerHTML = "destination:" + destinations[j];
        distance<%= a.id %>.innerHTML = "distance: " + results[j].distance.text;
        time_text.innerHTML = "commuting time"
        walking<%= a.id %>.innerHTML = "walking: " + results[j].duration.text;
        j++;
      <% end %>
    }
  }

  var service2 = new google.maps.DistanceMatrixService();
  distance_settings.travelMode = google.maps.TravelMode.BICYCLING;
  service2.getDistanceMatrix(distance_settings, callback2);
}

function callback2(response, status) {
  if (status != google.maps.DistanceMatrixStatus.OK) {
    alert('Error was: ' + status);
  } else {
    var origins = response.originAddresses;
    var destinations = response.destinationAddresses;
    
    var origins = response.originAddresses;
    // console.log(origins[0]); return the calculated address for that location
    var destinations = response.destinationAddresses;
    // console.log(destinations[0]); return the calculated address for that location
    
    // there is only one row because there is only one origin  
    for (var i = 0; i < origins.length; i++) {
      var results = response.rows[i].elements;
      var j = 0;
      <% @filtered_activities_by_time.each do |a| %>
        biking<%= a.id %>.innerHTML = "biking: " + results[j].duration.text;
        // console.log(results[j].duration.text);
        j++;
      <% end %>
    }
  }

  var service3 = new google.maps.DistanceMatrixService();
  distance_settings.travelMode = google.maps.TravelMode.DRIVING;
  service3.getDistanceMatrix(distance_settings, callback3);
}

function callback3(response, status) {
  if (status != google.maps.DistanceMatrixStatus.OK) {
    alert('Error was: ' + status);
  } else {
    var origins = response.originAddresses;
    var destinations = response.destinationAddresses;
    
    var origins = response.originAddresses;
    // console.log(origins[0]); return the calculated address for that location
    var destinations = response.destinationAddresses;
    // console.log(destinations[0]); return the calculated address for that location
    
    // there is only one row because there is only one origin  
    for (var i = 0; i < origins.length; i++) {
      var results = response.rows[i].elements;
      var j = 0;
      <% @filtered_activities_by_time.each do |a| %>
        driving<%= a.id %>.innerHTML = "driving: " + results[j].duration.text;
        j++;
      <% end %>
    }
  }
}


function showError(error) {
    switch(error.code) {
        case error.PERMISSION_DENIED:
            x.innerHTML = "User denied the request for Geolocation."
            break;
        case error.POSITION_UNAVAILABLE:
            x.innerHTML = "Location information is unavailable."
            break;
        case error.TIMEOUT:
            x.innerHTML = "The request to get user location timed out."
            break;
        case error.UNKNOWN_ERROR:
            x.innerHTML = "An unknown error occurred."
            break;
    }
}
</script>

app/views/layouts/_header.html.erb
<div>
	<div id= "header" class="page-container bored-header clearfix shift-with-hiw">
			<a href="/home/index" class="header-logo pull-left"> <img src="/assets/clock2.png"></a>
		<ul class="nav pull-right logged-out list-unstyled medium-right-margin">

		</ul>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ActivityApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <link href='https://fonts.googleapis.com/css?family=Lato:100' rel='stylesheet' type='text/css'>

  <link href='https://fonts.googleapis.com/css?family=Quicksand:300,700' rel='stylesheet' type='text/css'>

  <link href='https://fonts.googleapis.com/css?family=Quicksand:300' rel='stylesheet' type='text/css'>

  <script>UPLOADCARE_PUBLIC_KEY = "demopublickey";</script>

  <script src="https://ucarecdn.com/widget/1.0.1/uploadcare/uploadcare-1.0.1.min.js"></script>
  <script type="text/javascript">
	window.twttr=(function(d,s,id){var t,js,fjs=d.getElementsByTagName(s)[0];if(d.getElementById(id)){return}js=d.createElement(s);js.id=id;js.src="https://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);return window.twttr||(t={_e:[],ready:function(f){t._e.push(f)}})}(document,"script","twitter-wjs"));
	</script>

  <%= uploadcare_settings %>


</head>
<body>


<div id="fb-root"></div>
<script>(function(d, s, id) {
	  var js, fjs = d.getElementsByTagName(s)[0];
	  if (d.getElementById(id)) return;
	  js = d.createElement(s); js.id = id;
	  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&appId=161309977933&version=v2.0";
	  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));
</script>


<% flash.each do |name, msg| %>
      <%= content_tag :div, msg, class: name + " flash" %>
    <% end %>



<%= yield %>



</body>
</html>